[project]
name = "nicegui-experiments"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.128.0",
    "flask>=3.1.2",
    "jose>=1.0.0",
    "nicegui>=3.6.1",
    "numpy>=2.4.2",
    "supabase>=2.27.2",
]
